### ISSUE TITLE
Permision for modpack

### ISSUE THREAD

**Issue by mightydanp** [draknyte1/GTplusplus#24]
I would like permission to use in my modpack

**Comment by draknyte1** [comment]
Because I edited the front page, I forgot to re-add mod pack permissions for people. So for future, I will just link directly to here. 

ModPack T&C; you as a user are free to use GT++ however you wish. I do not require written forms asking for permission and will ignore any after this. Posting on the IC2 forum page and letting me know is appreciated, but not required. 

http://forum.industrial-craft.net/index.php?page=Thread&threadID=13325

**Comment by draknyte1** [comment]
For anyone else looking to use this project or parts within, please refer to the license posted on the GT++ main project page itself. All code contained from the APIs or mods of others has been left intact for the purpose of education. Please, use it responsibly.
