### ISSUE TITLE
Multi-Machine doesn't run for long

### ISSUE THREAD

**Issue by Wolozo7** [draknyte1/GTplusplus#257]
V10

Multi-Machine runs for ~12 operations, then turns off. Trying to reactivate it produces the usual 'turns on for a splitsecond, consumes items, then turns off'. The multiblock is supplied with a creative energy buffer, scanning the energy hatch shows that it contains energy :thinking:

**Comment by draknyte1** [comment]
Probably pollution related~

**Comment by Wolozo7** [comment]
Pollution in my test chunk is 50k, the multi itself doesn't produce any.

**Comment by draknyte1** [comment]
Try whack a muffler on it. 
If it has one, idk. 

Will further investigate.

**Comment by Prewf** [comment]
i tested a few weeks back, but the "magnetize" mode multi-machine would exhibit this behavior. the best way to describe it was that after a certain amount of eu had been used by the multiblock, it would cease to work any further. don't know how much that description helps. it could also just be time-based maybe?

I'm certain it wasn't due to a lack of power or anything like that. at the time, i was also testing other gt++ multi's with the same simple power setup, which was a couple of hv solar panels hooked up to an hv energy hatch; i tested the sifter/macerator/centrifurge/thermal cent/ore washer/electrolyzer/plate bender/extruder/wiremill. those all seemed to work fine.

**Comment by Prewf** [comment]
found the issue. it's like you suggested @draknyte1, it needs a muffler hatch. I put it on the top center and it worked perfectly.
