### ISSUE TITLE
Crash on both server and client when Github can't be reached

### ISSUE THREAD

**Issue by Ethryan** [draknyte1/GTplusplus#27]
gregtech-5.09.26pre
GT-PlusPlus-1.4.8.6-release
please do something to fix this
[crash-2016-10-21_20.58.02-client.txt](https://github.com/draknyte1/GTplusplus/files/545297/crash-2016-10-21_20.58.02-client.txt)

**Comment by draknyte1** [comment]
It already was, it's only in the 1.4.9 dev releases currently..

**Comment by draknyte1** [comment]
I think this is related to github being down on older versions of GT++.
There's a total lack of 'check if the web exists' in the first few versions with a version comparison.
draknyte1/GTplusplus@242dba0#diff-1d1442ff4001a2c1fe6b245ef4197e02 - It's fixed from 1.4.9, which will be out today/tomorrow~ Otherwise the Latest Dev version should be sufficient until then.
