### ISSUE TITLE
suggestion: ic2 crop greenhouse for gt:nh

### ISSUE THREAD

**Issue by Prewf** [draknyte1/GTplusplus#278]
here's an idea for a multiblock you could maybe work on in the distant future: a "greenhouse" of sorts that would allow one to do ic2 crop breeding inside it. it would be like a cleanroom, but for ic2 crops. essentially it would simulate the effects of a swamp biome and a height of 240+ (both of which requirements right now to grow ic2 crops without the help of extra water/fertilizer)

in terms of gameplay, it would help make ic2 crops a little more viable in that, you don't need to actively look for swamp biomes or go stupidly high up in the air just to grow some crops. the other big thing is that it would allow for plots of crops in a "vertical" set up, because right now, crops won't grow without a direct line of sight to the sun. so this kind of forces you to spread "horizontally" only, if that makes sense. since the greenhouse would get around that requirement, you could set up vertical "layers" of greenhouses as well as horizontal

**Comment by bartimaeusnek** [comment]
crops won't grow without a direct line of sight to the sun. <- wrong.
both of which requirements right now to grow ic2 crops without the help of extra water/fertilizer <- wrong.

you can grow them anywhere where you got light (even torches work). biome and height are just required for max statt crops.

**Comment by sthegreat** [comment]
So this is overall a pretty good suggestion, but it is probably somewhat unnecessary because these things aren't really a huge problem anyways - you can use a forestry farm to fertilize (or cropmatron if you have tons of fertilizer) and you will be able to grow max crops anywhere, albeit with an efficiency loss. The bigger problems with ic2 crops are how hard they are to duplicate and how weak the drops are, which should probably be looked at in a separate issue at some point.

Also, if this is added, make it big enough to fit a whole forestry farm in it pls
