### ISSUE TITLE
Missing Recipes from 1.4.9-prerelease-2

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#30]
As explained here, some recipes are missing - https://github.com/draknyte1/GTplusplus/commit/c70c95e3554d1d58870e2440b9f744abfbe47800

After I fix this, 1.4.9 will be out.

**Comment by draknyte1** [comment]
@GregoriusT @Bloodasp - It's because I have mixer recipes that have very similar inputs, yet totally different EU/T, time and Output, yet I think it's flagging them as duplicate/overlapping recipes.

How do I avoid this and what are the limits of how close recipes can be?

**Comment by draknyte1** [comment]
Proposition: Implement some kind of Large Mixer.

Not sure whether or not to make it a multiblock, or add some single block forms and a far more efficient/multi-use multiblock variant.

**Comment by leagris** [comment]
On a multi-block you can get as much as 16 input slots per bus and have multiple fluid input hatches. Be it a mixer or an alloy blast-furnace, as long as recipes depends on ingredients proportions rather than ingredient kind, you need a recipe selector independent of the ingredients available in the different input bus slots and fluid hatches.

**Comment by draknyte1** [comment]
Maximum input size will be restricted to 9, single hatch. No more, no less.

**Comment by draknyte1** [comment]
https://github.com/draknyte1/GTplusplus/commit/10a120808e9c6199b179224fe11cde89d9fd54f2

![2016-10-25_02 25 47](https://cloud.githubusercontent.com/assets/3060479/19665976/20e2c556-9a8b-11e6-9ec7-75af68698eb0.png)

![2016-10-25_08 12 04](https://cloud.githubusercontent.com/assets/3060479/19665943/06845cba-9a8b-11e6-89c3-be91facd24a0.png)
![2016-10-25_08 12 18](https://cloud.githubusercontent.com/assets/3060479/19665946/0884520e-9a8b-11e6-8e0e-5fb583d28eb5.png)


![2016-10-25_08 12 07](https://cloud.githubusercontent.com/assets/3060479/19665955/1341253c-9a8b-11e6-8595-ebdd424d9976.png)
![2016-10-25_08 12 15](https://cloud.githubusercontent.com/assets/3060479/19665959/160f1d82-9a8b-11e6-9615-68b6c2f3132f.png)

![2016-10-25_03 27 41](https://cloud.githubusercontent.com/assets/3060479/19665984/2cea35b4-9a8b-11e6-9a23-9c0d8cc4b43b.png)

**Comment by GregoriusT** [comment]
The Recipes have to be instantly identifyable, if you have a Recipe
with just two inputs, lets say A and B, and you add a Recipe with 3
Inputs, but it also contains A and B, since it is a Recipe with A, B
and C, then the ABC Recipe will never be added, because the AB Recipe
has priority. As soon as something could cause two Recipes to react to
one Set of Inputs, it will never work properly. And I explained that
to you on IRC aswell, Alkalus.

The only way to "fix" that would be to have the Selector Circuits
(Integrated Circuits in GT5) select the wanted Recipe, like many
Machines already do. But that Circuit would have to be inside all
Recipes, including the AB Recipe, that caused the problem in the first
place.

**Comment by draknyte1** [comment]
Adding circuits didn't really fix it. 
Expanding inputs to nine did.
