### ISSUE TITLE
[balance] Stop using turbines when <10 durability in Pollution Scrubber

### ISSUE THREAD

**Issue by richardhendricks** [draknyte1/GTplusplus#312]
The PS uses turbines really fast.  It would be nice if it would not use them to destruction, instead stopping a few steps short.  That way they could be recycled in the disassembler.  It would allow for setting up a pollution system

detector -> activates scrubber
detectoer 2 -> activates alarm if pollution gets really high, notify player to replace turbines in scrubber.

**Comment by draknyte1** [comment]
The durability consumed cannot be tweaked any lower, with durability being eaten less often (Due to the Turbines being GT Tools and weird limitations of them).

As is, Pollution was __Never__ intended to have a way to be cleared up. @blood-Asp was always against such additions, so my solution was never meant to be efficient or player friendly. This is to extend allow removal, but you're going to have to work for it. It does however present an option for removal, which in itself, cannot be fully automated.

Saving Turbines at low durability could be a feature I'll add though, however It'll effect your removal efficiency.
