### ISSUE TITLE
GT:NH Staballoy produces hot ingots in the ebf

### ISSUE THREAD

**Issue by Anarack** [draknyte1/GTplusplus#341]
# Issue Title  
GT:NH 2.0.4.6
GT++ 1.7.1.01
## Expected Behavior
you told me it should not produce hot ingots

## Current Behavior
staballoy dust in a ebf produces hot ingots

## Possible Solution
make it not produce hot ingots

## Game Environment
GT:NH

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Multi Player?

**Comment by Highbeam** [comment]
I don't see the problem here.

If you want to make Staballoy before you have the Blast Alloy Furnace then you have to go through the EBF and Vacuum Freezer process.  Once you have the Blast Alloy Furnace, you make staballoy in fluid form which means you don't need vacuum freezer anymore, you just fluid solidify it...

**Comment by draknyte1** [comment]
I don't recall why I thought this was an issue now.
If either of you two remember, let me know.
