### ISSUE TITLE
GT Wrench on Crop Harvester drops Basic Machine Casing

### ISSUE THREAD

**Issue by xhek** [draknyte1/GTplusplus#435]
Was told to post this issue on this github instead of the GTNH one
https://github.com/GTNewHorizons/NewHorizons/issues/4195

## Expected Behavior
Basic Machine Casing dropped instead of machine, the machine should have dropped

## Current Behavior
Tried to destroy the Crop Harvester (IC2) with the GT Wrench to replace the machine like every other machine

## Possible Solution
Make the GT Wrench disassemble IC2 machines, almost all items used in the recipe for the Crop Harvester are GT Items

## Game Environment
 Include as many relevant details about the game environment or modpack you experienced the bug in/on.
 If you are using a Modpack:
 * Modpack Name:  GTNH
 * Version used: 2.0.6.8

Also include:
 * Gregtech version: 5.09.33.10
 * IC2 version: 2-2.2.828-exp

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [ x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x ]    Multi Player?

**Comment by xhek** [comment]
Fixed in GTNH 6.8+

**Comment by Dream-Master** [comment]
in GTNH 2.0.6.8 is gt++ 89 lastest build

**Comment by draknyte1** [comment]
It turns out it wasn't actually working in an Obfuscated environment.

Anyway, Fixed by these two commits:
https://github.com/draknyte1/GTplusplus/commit/9ee7517f6b683ca604c87a397c0bf57abfc7aa2c#diff-eb86a09bd136233ccb7d025e97269daf
https://github.com/draknyte1/GTplusplus/commit/593b972224ce31c19e5890212edfbf2818fd7759#diff-eb86a09bd136233ccb7d025e97269daf
